name: Go
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy
    runs-on: [threemin]
    steps:
    - name: Check out
      uses: actions/checkout@v1
    - name: copy and restart
      run: |
        pwd
        ls -l
        mv _work/3minute-admin/3minute-admin /home/ubuntu/nginx/static
        cd /home/ubuntu/nginx
        docker-compose restart
