name: Go
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy
    runs-on: [threemin]
    steps:
    - name: Check out
      uses: actions/checkout@v1
    - name: copy and restart
      run: |
        mkdir -p /home/ubuntu/nginx/static
        rm -rf /home/ubuntu/nginx/static/*
        mv * /home/ubuntu/nginx/static/
        cd /home/ubuntu/nginx
        docker-compose restart
